"""Report read-model API, independent from HWP/PDF adapters."""

from .model import (
    CalculationEntry,
    CriterionExecution,
    EnergyAnalysisSection,
    EngineerEntry,
    EquipmentEntry,
    ImprovementPlanEntry,
    InspectionItemResult,
    InspectionTargetSection,
    PhotoEntry,
    PreviousComparisonEntry,
    ReportDocument,
    RootCauseEntry,
    SiteSection,
    SystemReviewEntry,
    report_document_to_dict,
)
from .service import REPORT_MODEL_VERSION, build_report_document
from .hwp_adapter import (
    HwpAdapterError,
    HwpComUnavailableError,
    HwpGenerationResult,
    HwpTextAdapter,
    TemplateContractError,
    parse_hwp_field_list,
)
from .hwp_repeat_adapter import HwpComRepeatWriter, HwpReportAdapter
from .repeat_service import (
    RepeatItemRow,
    RepeatRenderPlan,
    TargetRepeatBlock,
    build_repeat_render_plan,
)
from .template_contract import (
    MINIMAL_HWP_CONTRACT,
    MINIMAL_REPEAT_HWP_CONTRACT,
    ContractValidationResult,
    FieldContract,
    RepeatColumnContract,
    RepeatSectionContract,
    TemplateContract,
    resolve_field_value,
    validate_template_contract,
)

__all__ = [
    "REPORT_MODEL_VERSION",
    "CalculationEntry",
    "CriterionExecution",
    "EnergyAnalysisSection",
    "EngineerEntry",
    "EquipmentEntry",
    "ImprovementPlanEntry",
    "InspectionItemResult",
    "InspectionTargetSection",
    "PhotoEntry",
    "PreviousComparisonEntry",
    "ReportDocument",
    "RootCauseEntry",
    "SiteSection",
    "SystemReviewEntry",
    "build_report_document",
    "report_document_to_dict",
    "HwpAdapterError",
    "HwpComUnavailableError",
    "HwpGenerationResult",
    "HwpTextAdapter",
    "TemplateContractError",
    "parse_hwp_field_list",
    "HwpComRepeatWriter",
    "HwpReportAdapter",
    "RepeatItemRow",
    "RepeatRenderPlan",
    "TargetRepeatBlock",
    "build_repeat_render_plan",
    "ContractValidationResult",
    "FieldContract",
    "MINIMAL_HWP_CONTRACT",
    "MINIMAL_REPEAT_HWP_CONTRACT",
    "RepeatColumnContract",
    "RepeatSectionContract",
    "TemplateContract",
    "resolve_field_value",
    "validate_template_contract",
]
