"""Equipment catalog."""

EQUIPMENT_LIST = [{'name': '냉동기', 'rate': 50, 'unit': '대'},
 {'name': '냉각탑', 'rate': 50, 'unit': '대'},
 {'name': '축열조', 'rate': 100, 'unit': '대'},
 {'name': '보일러', 'rate': 50, 'unit': '대'},
 {'name': '열교환기', 'rate': 50, 'unit': '대'},
 {'name': '팽창탱크', 'rate': 100, 'unit': '대'},
 {'name': '펌프(냉난방·급수)', 'rate': 20, 'unit': '대'},
 {'name': '신재생에너지(태양열·지열)', 'rate': 100, 'unit': '대'},
 {'name': '연료전지', 'rate': 100, 'unit': '대'},
 {'name': '패키지에어컨', 'rate': 20, 'unit': '대'},
 {'name': '항온항습기', 'rate': 20, 'unit': '대'},
 {'name': '공기조화기', 'rate': 20, 'unit': '대'},
 {'name': '팬코일유닛', 'rate': 10, 'unit': '대'},
 {'name': '환기설비', 'rate': 20, 'unit': '대'},
 {'name': '필터', 'rate': 100, 'unit': '대'},
 {'name': '위생기구설비', 'rate': 100, 'unit': '식'},
 {'name': '급수·급탕설비', 'rate': 100, 'unit': '식'},
 {'name': '고·저수조', 'rate': 100, 'unit': '식'},
 {'name': '오·배수통기 및 우수배수설비', 'rate': 100, 'unit': '식'},
 {'name': '오수정화설비', 'rate': 100, 'unit': '식'},
 {'name': '물재이용설비', 'rate': 100, 'unit': '식'},
 {'name': '배관설비', 'rate': 100, 'unit': '식'},
 {'name': '덕트설비', 'rate': 100, 'unit': '식'},
 {'name': '보온설비', 'rate': 100, 'unit': '식'},
 {'name': '자동제어설비', 'rate': 100, 'unit': '식'},
 {'name': '방음·방진·내진설비', 'rate': 100, 'unit': '식'}]
